"""Add learning_outcomes to Course

Revision ID: 5985f9f9d98b
Revises: f815f822a048
Create Date: 2026-03-15 22:50:47.700882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5985f9f9d98b'
down_revision: Union[str, None] = 'f815f822a048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'learning_outcomes')
    # ### end Alembic commands ###
