"""add watched_seconds to lesson_progress

Revision ID: 7af1e78cd9ad
Revises: f698427883ca
Create Date: 2026-04-18 00:16:03.894466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af1e78cd9ad'
down_revision: Union[str, None] = 'f698427883ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_progress', sa.Column('watched_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lesson_progress', sa.Column('video_duration', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_progress', 'video_duration')
    op.drop_column('lesson_progress', 'watched_seconds')
    # ### end Alembic commands ###
