"""add_enrollment_status_and_progress

Revision ID: f815f822a048
Revises: d32064f71ed4
Create Date: 2026-03-14 21:17:43.740940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f815f822a048'
down_revision: Union[str, None] = 'd32064f71ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('status', sa.String(length=50), server_default='not-started', nullable=False))
    op.add_column('enrollments', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'progress')
    op.drop_column('enrollments', 'status')
    # ### end Alembic commands ###
